manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import:
        - app/west.yml
        - app/CMakeLists.txt
        - app/Kconfig
  self:
    path: config