---
name: Build ZMK Firmware
on:
  push:
    branches:
      - jogrefer-layout-v1
  pull_request:
    branches:
      - jogrefer-layout-v1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: Install west and dependencies
        run: |
          sudo apt update
          python -m pip install --upgrade pip
          sudo apt-get install -y git ninja-build flex bison gperf libfl-dev zlib1g-dev libncurses5-dev dfu-util device-tree-compiler wget python3-venv
          sudo apt-get -y -f install
          pip3 install -U west
          pwd
      - name: Initialize west and Folder Structure
        run: |
          west init -l
          pwd
      - name: West update
        run: |
          west update
          pwd
      - name: Build
        run: |
          west -vv status
          west build -b nice_nano_v2 -p always
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v3
        with:
          name: zmk-firmware
          path: zmk-config/build/jogrefer.uf2