name: Build ZMK Firmware

# manifest:
#   version: 0.7
#   remotes:
#     - name: zephyrproject-rtos
#       url-base: https://github.com/zephyrproject-rtos
#   projects:
#     - name: zephyr
#       repo-path: zephyr
#       revision: main
#       import: true
#   self:
#     path: .

on:
  push:
    branches:
      - jogrefer-layout-v1  # Replace 'main' with your branch name if different
  pull_request:
    branches:
      - jogrefer-layout-v1  # Replace 'main' with your branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository #code
      uses: actions/checkout@v3
      with:
        path: .  # Clona el repositorio directamente en $GITHUB_WORKSPACE

      - name: Clean workspace # ¡NUEVO PASO!
        run: rm -rf $GITHUB_WORKSPACE/* .git # Elimina todo excepto .git

      - name: Checkout code (Cleaning) # ¡NUEVO PASO!
        uses: actions/checkout@v3
        with:
          path: .

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install west and other dependencies
      run: |
        pip install west
        sudo apt-get update
      # python -m pip install --upgrade pip
        sudo apt-get install -y git ninja-build flex bison gperf libfl-dev zlib1g-dev libncurses5-dev dfu-util device-tree-compiler wget

    - name: Initialize west and update
      run: |
        cd $GITHUB_WORKSPACE
        west init -l .
        west update

    - name: Build firmware
      run: west build -b nrf52840_m2 -d build/nrf52840_m2 .  #Replace 'jogrefer' with your actual board name

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v3
      with:
        name: zmk-firmware
        path: build/zmk/jogrefer.uf2  # Adjust the path as necessary