#     ---
#     name: Build ZMK Firmware
#     on:
#       push:
#         branches:
#           - jogrefer-layout-v1
#       pull_request:
#         branches:
#           - jogrefer-layout-v1
#     jobs:
#       build:
#         runs-on: ubuntu-latest
#         steps:
#           - name: Checkout repository
#        uses: actions/checkout@v2
#        with:
#          submodules: true 
#          path: .
#           - name: Set up Python
#        uses: actions/setup-python@v3
#        with:
#          python-version: 3.x
#           - name: Install west and dependencies
#        run: |
#          sudo apt update
#          python -m pip install --upgrade pip
#          sudo apt-get install -y git ninja-build flex bison gperf libfl-dev zlib1g-dev libncurses5-dev dfu-util device-tree-compiler wget python3-venv
#          sudo apt-get -y -f install
#          pip3 install -U west
#          pwd
#           - name: Initialize west and Folder Structure
#        run: |
#          west init -l .
#          pwd
#          tree -L 1 .
#          cd ..
#          pwd
#           - name: West update
#        run: |
#          cd .
#          west update
#          cd ..
#          pwd
#           - name: DEBUG
#        run: west -vv status
#           - name: Build
#             run: |
#               pwd
#               tree -L 1 .
#               west build -d /build -p -b nice_nano_v2 -- -DCONFIG_ZMK_SLEEP=y -DSHIELD=jogrefer -DZMK_CONFIG=/zmk-config/config/
#           - name: Upload firmware artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: zmk-firmware
#          path: zmk-config/build/jogrefer.uf2 

name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - config/west.yml
      - boards/shields/jogrefer/**
      - config/*.conf
      - boards/**
      - build.yaml
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main


