---
name: Build ZMK Firmware
on:
  push:
    branches:
      - jogrefer-layout-v1
  pull_request:
    branches:
      - jogrefer-layout-v1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: zmk-config
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: Install west and dependencies
        run: |
          sudo apt update
          python -m pip install --upgrade pip
          pip3 install -U west
          sudo apt-get -f install
      - name: Initialize west
        run: |
          cd zmk-config
          west init -l .
          west config manifest.path west.yml
          cd ..
      - name: West update
        run: |
          cd zmk-config
          west -v update --path "/home/runner/work/zmk-config/zmk-config"
      - name: West build
        run: |
          cd zmk-config
          west build -b nice_nano_v2 -p always
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v3
        with:
          name: zmk-firmware
          path: zmk-config/build/jogrefer.uf2