name: Build ZMK Firmware

on:
  push:
    branches:
      - jogrefer-layout-v1  # Replace 'main' with your branch name if different
  pull_request:
    branches:
      - jogrefer-layout-v1  # Replace 'main' with your branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code #repository
      uses: actions/checkout@v3
      with:
        path: zmk-config  # Clona el repositorio directamente en $GITHUB_WORKSPACE

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install west and other dependencies
      run: |
        pip install west
        sudo apt-get update
      # python -m pip install --upgrade pip
        sudo apt-get install -y git ninja-build flex bison gperf libfl-dev zlib1g-dev libncurses5-dev dfu-util device-tree-compiler wget

    - name: Initialize west
      run: |
        cd $GITHUB_WORKSPACE
        west init -l .
        west config manifest.path west.yml
        cd $GITHUB_WORKSPACE

      - name: West update
        run: |
          cd $GITHUB_WORKSPACE/zmk-config
          west update

      - name: West build
        run: |
          cd $GITHUB_WORKSPACE/zmk-config
          west build -b nrf52840_m2 -d build/nrf52840_m2 .

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v3
      with:
        name: zmk-firmware
        path: zmk-config/build/zephyr/zmk.uf2